### 1. Crear un nuevo Sprint
POST http://127.0.0.1:8000/sprint
Content-Type: application/json

{
  "nombre": "Sprint 1: Configuración e Interfaces",
  "fecha_inicio": "2026-05-18",
  "fecha_fin": "2026-05-29"
}

###

### 2. Consultar todos los Sprints
GET http://127.0.0.1:8000/sprint

###

### 3. Crear un ítem en la retrospectiva (Logro, Impedimento o Acción)
POST http://127.0.0.1:8000/retro_items
Content-Type: application/json

{
  "sprint_id": 1,
  "categoria": "logro",
  "descripcion": "Logramos desplegar el primer microservicio a tiempo."
}

###

### 4. Visualizar la pizarra completa de un Sprint (Sprints + Acciones anteriores)
GET http://127.0.0.1:8000/retro_items/sprint/1

###

### 5. Consultar el historial global de todos los ítems
GET http://127.0.0.1:8000/retro_items

###

### 6. Actualizar un ítem (Modificar texto o marcar acción como cumplida)
PUT http://127.0.0.1:8000/retro_items/1
Content-Type: application/json

{
  "descripcion": "Logramos desplegar el primer microservicio a tiempo (Editado)",
  "cumplida": 1
}

###

### 7. Eliminar un ítem de la retrospectiva
DELETE http://127.0.0.1:8000/retro_items/1