### APIS DE SPRINTS

### consultar todos los sprints
GET http://127.0.0.1:8000/sprint

### consultar sprint
GET http://127.0.0.1:8000/sprint/1

### crear sprint
POST http://127.0.0.1:8000/sprint
Content-Type: application/json

{
    "nombre": "Sprint 1: Configuración e Interfaces",
    "fecha_inicio": "2026-05-18",
    "fecha_fin": "2026-05-29"
}

### modificar sprint
PUT http://127.0.0.1:8000/sprint/1
Content-Type: application/json

{
    "nombre": "Sprint 1: Interfaces Modificadas",
    "fecha_inicio": "2026-05-18",
    "fecha_fin": "2026-06-05"
}

### borrar sprint
DELETE http://127.0.0.1:8000/sprint/1

### APIS DE RETROSPECTIVAS (RETRO ITEMS)

### consultar todos los items de retrospectiva
GET http://127.0.0.1:8000/retro_items

### consultar historial global de items
GET http://127.0.0.1:8000/retro_items/historial

### visualizar la pizarra de un sprint específico
GET http://127.0.0.1:8000/retro_items/sprint/1

### crear item de retrospectiva (logro, impedimento o accion)
POST http://127.0.0.1:8000/retro_items
Content-Type: application/json

{
    "sprint_id": 1,
    "categoria": "logro",
    "descripcion": "Logramos desplegar el primer microservicio a tiempo."
}

### modificar item de retrospectiva
PUT http://127.0.0.1:8000/retro_items/1
Content-Type: application/json

{
    "descripcion": "Logramos desplegar el primer microservicio a tiempo (Editado)",
    "cumplida": 1
}

### borrar item de retrospectiva
DELETE http://127.0.0.1:8000/retro_items/1